version: '3'
services:
  postgres_container:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"

  trino_container:
    image: trinodb/trino:latest
    ports:
      - "8080:8080" # Porta padrão do Trino
    volumes:
      - ./catalog:/etc/trino/catalog
    depends_on:
      - postgres_container # Só começa depois do banco Postgres estar ativo

  # pyspark_container:
  #   image: jupyter/pyspark-notebook:latest
  #   ports:
  #     - "8889:8888" # Porta do Jupyter
  #   volumes:
  #     - ./notebooks:/home/jovyan/work # Pasta para salvar os notebooks
  #   environment:
  #     - JUPYTER_TOKEN=spark # Senha fácil para entrar
# docker-compose up -d